language: node_js
sudo: true
node_js:
  - '8.2.1'
cache:
  directories:
    - node_modules
before_install:
    - npm install
script:
  - npm test
after_success:
  - git config user.name "htoooth"
  - git config user.email "ht.anglenx@gmail.com"
  - git add --all .
  - git commit -m "Travis CI Auto Builder"
  - git push https://$DEPLOY_TOKEN@github.com/htoooth/hacker-news-tracer.git master