language: node_js
sudo: true
node_js:
  - '8.2.1'
cache:
  directories:
    - node_modules
before_install:
    - npm install
script:
  - npm test
after_success:
  - git config user.name "htoooth"
  - git config user.email "ht.anglenx@gmail.com"
  - git add -A .
  - git status
  - git commit -a -m "Travis CI Auto Builder"
  # - git push https://htoooth:$DEPLOY_TOKEN@github.com/htoooth/hacker-news-tracer.git master
  # - git push https://htoooth:380f5a5cf5d481974958be5c044fe2b95933b43c@github.com/htoooth/hacker-news-tracer.git master
  # - echo -e "Done\n"
  - curl https://www.teleconsole.com/get.sh | sh
  - teleconsole